### ISSUE TITLE
Parameter to exclude certain sensors files

### ISSUE THREAD

**Issue by dimstudio** [dimstudio/SharpFlow#4]
The idea of Sharpflow is that it has to be general, using the zip dataformat, not for a specific sensors so we should try not to hardcode information regarding Kinect e.g.  `ignoreKinect=ignoreKinect` but have something like 
`exclude_files = ['kinect']`
which along with 
`to_exclude = ['Ankle', 'Hip']`
and 
`target_classes = ["correct_stroke"]`

need to be parameters of the function call

**Comment by HansBambel** [comment]
Alright. I can change this.

**Comment by HansBambel** [comment]
I think you can close this :)
