### ISSUE TITLE
Multiclass classifier

### ISSUE THREAD

**Issue by dimstudio** [dimstudio/SharpFlow#6]
What is the actual meaning of the Multiclass Classifier?
As I understand it combines the results of 3 classes into one. How can it make it boolean?

For instance `models/model_classRate_classDepth_classRelease.h5`('Test accuracy:', 0.527339)
('Test loss:', -42.63868981288386).

**Comment by dimstudio** [comment]
Edit: on my other CPR dataset also the single class performs bad.

**Comment by dimstudio** [comment]
What is the actual meaning of the Multiclass Classifier? 
As I understand it combines the results of 3 classes into one. How can it make it boolean?

**Comment by HansBambel** [comment]
> As I understand it combines the results of 3 classes into one. How can it make it boolean?

The network will give an output for every single one of the classes at the end. For example classRate = 1, classDepth = 0, classRelease = 1.
These values can then be used to compare them with their targets and calculate the accuracy and loss.

**Comment by dimstudio** [comment]
With the new `CPR_feedback` dataset now we have 5 targets.

If I set the `target_classes` as
`target_classes = ['classRelease' , 'classDepth', 'classRate', 'armsLocked', 'bodyWeight']`
I get an overall accuracy of the model. How can I get the accuracy of the single models? do I need to train them individually? (e.g. `target_classes = ['classRelease']`)

**Comment by HansBambel** [comment]
> do I need to train them individually?

Not necessarily, we would need to dissect the testing function for this.

**Comment by HansBambel** [comment]
I created a function (`acc_prec_rec_modules`) for checking the modules performance. For now this is done only at testing time, because it would be too verbose otherwise.

Done in #19
